Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
TFour = np.fft.fft(x_cont)/len(x_cont)
freq = np.fft.fftfreq(t.shape[-1], 1/SAMPLE_RATE)

figTF, axTF = plt.subplots()
axTF.stem(freq,np.abs(TFour),use_line_collection=True)
axTF.set_xlabel("Frecuencia [Hz]", fontsize=20)
axTF.set_ylabel("Magnitud", fontsize=20)
axTF.set_xlim(-15,15)
print(x_cont.shape)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      2[0m freq [38;5;241m=[39m np[38;5;241m.[39mfft[38;5;241m.[39mfftfreq(t[38;5;241m.[39mshape[[38;5;241m-[39m[38;5;241m1[39m], [38;5;241m1[39m[38;5;241m/[39mSAMPLE_RATE)
[1;32m      4[0m figTF, axTF [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[0;32m----> 5[0m [43maxTF[49m[38;5;241;43m.[39;49m[43mstem[49m[43m([49m[43mfreq[49m[43m,[49m[43mnp[49m[38;5;241;43m.[39;49m[43mabs[49m[43m([49m[43mTFour[49m[43m)[49m[43m,[49m[43muse_line_collection[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m      6[0m axTF[38;5;241m.[39mset_xlabel([38;5;124m"[39m[38;5;124mFrecuencia [Hz][39m[38;5;124m"[39m, fontsize[38;5;241m=[39m[38;5;241m20[39m)
[1;32m      7[0m axTF[38;5;241m.[39mset_ylabel([38;5;124m"[39m[38;5;124mMagnitud[39m[38;5;124m"[39m, fontsize[38;5;241m=[39m[38;5;241m20[39m)

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/jupyter-book-env/lib/python3.10/site-packages/matplotlib/__init__.py:1465[0m, in [0;36m_preprocess_data.<locals>.inner[0;34m(ax, data, *args, **kwargs)[0m
[1;32m   1462[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(func)
[1;32m   1463[0m [38;5;28;01mdef[39;00m [38;5;21minner[39m(ax, [38;5;241m*[39margs, data[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m   1464[0m     [38;5;28;01mif[39;00m data [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m-> 1465[0m         [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[43max[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;28;43mmap[39;49m[43m([49m[43msanitize_sequence[49m[43m,[49m[43m [49m[43margs[49m[43m)[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   1467[0m     bound [38;5;241m=[39m new_sig[38;5;241m.[39mbind(ax, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   1468[0m     auto_label [38;5;241m=[39m (bound[38;5;241m.[39marguments[38;5;241m.[39mget(label_namer)
[1;32m   1469[0m                   [38;5;129;01mor[39;00m bound[38;5;241m.[39mkwargs[38;5;241m.[39mget(label_namer))

[0;31mTypeError[0m: Axes.stem() got an unexpected keyword argument 'use_line_collection'
TypeError: Axes.stem() got an unexpected keyword argument 'use_line_collection'

