Traceback (most recent call last):
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\util.py", line 96, in ensure_async
    result = await obj
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\jupyter_client\channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Agustin\Anaconda3\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\client.py", line 754, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "C:\Users\Agustin\Anaconda3\lib\site-packages\nbclient\client.py", line 802, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['#Defino un vector x entre –π to +π', 't=np.arange(-3*np.pi,3*np.pi,0.001) ', '', '# Genera una senal cuadrada utilizando scipy', '#y=square(t) ']
...
['for i in range(n):', ' if i==0.0:', '    sum=sum+An[i]/2', ' else:', '    sum=sum+(An[i]*np.cos(i*t)+Bn[i]*np.sin(i*t))']
-------------------

